// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EnumCmdID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MCServer {

  /// <summary>Holder for reflection information generated from EnumCmdID.proto</summary>
  public static partial class EnumCmdIDReflection {

    #region Descriptor
    /// <summary>File descriptor for EnumCmdID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumCmdIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9FbnVtQ21kSUQucHJvdG8SCE1DU2VydmVyKmwKCUVudW1DbWRJRBIICgRO",
            "T05FEAASDQoJSEVBUlRCRUFUEAESEAoLU0VUVElOR19SRVEQkU4SEAoLU0VU",
            "VElOR19SRVMQkk4SEAoLRVhQSU5GT19SRVEQk04SEAoLRVhQSU5GT19SRVMQ",
            "lE5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MCServer.EnumCmdID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EnumCmdID {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    ///心跳包请求协议号
    /// </summary>
    [pbr::OriginalName("HEARTBEAT")] Heartbeat = 1,
    /// <summary>
    ///系统设置请求协议号
    /// </summary>
    [pbr::OriginalName("SETTING_REQ")] SettingReq = 10001,
    /// <summary>
    ///系统设置请求回包协议号
    /// </summary>
    [pbr::OriginalName("SETTING_RES")] SettingRes = 10002,
    /// <summary>
    ///实验信息请求协议号
    /// </summary>
    [pbr::OriginalName("EXPINFO_REQ")] ExpinfoReq = 10003,
    /// <summary>
    ///实验信息请求回包协议号
    /// </summary>
    [pbr::OriginalName("EXPINFO_RES")] ExpinfoRes = 10004,
  }

  #endregion

}

#endregion Designer generated code
