// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HeartBeatInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MagiCloud.NetWorks {

  /// <summary>Holder for reflection information generated from HeartBeatInfo.proto</summary>
  public static partial class HeartBeatInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for HeartBeatInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HeartBeatInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNIZWFydEJlYXRJbmZvLnByb3RvEhJNYWdpQ2xvdWQuTmV0V29ya3MiNAoN",
            "SGVhcnRCZWF0SW5mbxITCgtjdXJyZW50VGltZRgBIAEoBRIOCgZob3N0aXAY",
            "AiABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MagiCloud.NetWorks.HeartBeatInfo), global::MagiCloud.NetWorks.HeartBeatInfo.Parser, new[]{ "CurrentTime", "Hostip" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///心跳包信息
  /// </summary>
  public sealed partial class HeartBeatInfo : pb::IMessage<HeartBeatInfo> {
    private static readonly pb::MessageParser<HeartBeatInfo> _parser = new pb::MessageParser<HeartBeatInfo>(() => new HeartBeatInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeartBeatInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MagiCloud.NetWorks.HeartBeatInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeatInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeatInfo(HeartBeatInfo other) : this() {
      currentTime_ = other.currentTime_;
      hostip_ = other.hostip_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartBeatInfo Clone() {
      return new HeartBeatInfo(this);
    }

    /// <summary>Field number for the "currentTime" field.</summary>
    public const int CurrentTimeFieldNumber = 1;
    private int currentTime_;
    /// <summary>
    ///当前时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CurrentTime {
      get { return currentTime_; }
      set {
        currentTime_ = value;
      }
    }

    /// <summary>Field number for the "hostip" field.</summary>
    public const int HostipFieldNumber = 2;
    private string hostip_ = "";
    /// <summary>
    ///主机IP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hostip {
      get { return hostip_; }
      set {
        hostip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeartBeatInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeartBeatInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentTime != other.CurrentTime) return false;
      if (Hostip != other.Hostip) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentTime != 0) hash ^= CurrentTime.GetHashCode();
      if (Hostip.Length != 0) hash ^= Hostip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CurrentTime != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CurrentTime);
      }
      if (Hostip.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hostip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CurrentTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentTime);
      }
      if (Hostip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hostip);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeartBeatInfo other) {
      if (other == null) {
        return;
      }
      if (other.CurrentTime != 0) {
        CurrentTime = other.CurrentTime;
      }
      if (other.Hostip.Length != 0) {
        Hostip = other.Hostip;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CurrentTime = input.ReadInt32();
            break;
          }
          case 18: {
            Hostip = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
