// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommandID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MagiCloud.NetWorks {

  /// <summary>Holder for reflection information generated from CommandID.proto</summary>
  public static partial class CommandIDReflection {

    #region Descriptor
    /// <summary>File descriptor for CommandID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Db21tYW5kSUQucHJvdG8SEk1hZ2lDbG91ZC5OZXRXb3Jrcyq0AgoJQ29t",
            "bWFuZElEEggKBE5vbmUQABIcChhIZWFydGJlYXRfUGFja2V0X1JlcXVlc3QQ",
            "ARILCgdDb25uZWN0EAISFAoQUGF1c2VfQ29ubmVjdGlvbhADEhYKElJlc3Rv",
            "cmVfQ29ubmVjdGlvbhAEEhQKEEJyZWFrX0Nvbm5lY3Rpb24QBRIbChZTeXN0",
            "ZW1fU2V0dGluZ19SZXF1ZXN0EJFOEhsKFlN5c3RlbV9TZXR0aW5nX1JlY2Vp",
            "cHQQkk4SHAoXRXhwZXJpbWVudF9JbmZvX1JlcXVlc3QQk04SHAoXRXhwZXJp",
            "bWVudF9JbmZvX1JlY2VpcHQQlE4SGwoWV2luZG93X1dha2VfVXBfUmVxdWVz",
            "dBCVThIbChZXaW5kb3dfV2FrZV9VcF9SZWNlaXB0EJZOYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MagiCloud.NetWorks.CommandID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum CommandID {
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///心跳包请求协议号
    /// </summary>
    [pbr::OriginalName("Heartbeat_Packet_Request")] HeartbeatPacketRequest = 1,
    /// <summary>
    ///连接
    /// </summary>
    [pbr::OriginalName("Connect")] Connect = 2,
    /// <summary>
    ///挂起暂停
    /// </summary>
    [pbr::OriginalName("Pause_Connection")] PauseConnection = 3,
    /// <summary>
    ///恢复连接
    /// </summary>
    [pbr::OriginalName("Restore_Connection")] RestoreConnection = 4,
    /// <summary>
    ///断开连接
    /// </summary>
    [pbr::OriginalName("Break_Connection")] BreakConnection = 5,
    /// <summary>
    ///系统请求协议号
    /// </summary>
    [pbr::OriginalName("System_Setting_Request")] SystemSettingRequest = 10001,
    /// <summary>
    ///系统设置请求回包协议号
    /// </summary>
    [pbr::OriginalName("System_Setting_Receipt")] SystemSettingReceipt = 10002,
    /// <summary>
    ///实验信息请求协议号
    /// </summary>
    [pbr::OriginalName("Experiment_Info_Request")] ExperimentInfoRequest = 10003,
    /// <summary>
    ///实验信息请求回包协议号
    /// </summary>
    [pbr::OriginalName("Experiment_Info_Receipt")] ExperimentInfoReceipt = 10004,
    /// <summary>
    ///窗口唤醒请求
    /// </summary>
    [pbr::OriginalName("Window_Wake_Up_Request")] WindowWakeUpRequest = 10005,
    /// <summary>
    ///窗口唤醒回执
    /// </summary>
    [pbr::OriginalName("Window_Wake_Up_Receipt")] WindowWakeUpReceipt = 10006,
  }

  #endregion

}

#endregion Designer generated code
