// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EnumCmdID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MagiCloud.NetWorks
{

  /// <summary>Holder for reflection information generated from EnumCmdID.proto</summary>
  public static partial class EnumCmdIDReflection {

    #region Descriptor
    /// <summary>File descriptor for EnumCmdID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumCmdIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9FbnVtQ21kSUQucHJvdG8SCE1DU2VydmVyKsoBCglFbnVtQ21kSUQSCAoE",
            "Tk9ORRAAEg0KCUhFQVJUQkVBVBABEgsKB0NPTk5FQ1QQAhIJCgVQQVVTRRAD",
            "EgsKB1JFU1RPUkUQBBIJCgVCUkVBSxAFEhAKC1NFVFRJTkdfUkVREJFOEhAK",
            "C1NFVFRJTkdfUkVTEJJOEhAKC0VYUElORk9fUkVREJNOEhAKC0VYUElORk9f",
            "UkVTEJROEhUKEFdJTkRPV1dBS0VVUF9SRVEQlU4SFQoQV0lORE9XV0FLRVVQ",
            "X1JFUxCWTmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MagiCloud.NetWorks.EnumCmdID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EnumCmdID {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    ///心跳包请求协议号
    /// </summary>
    [pbr::OriginalName("HEARTBEAT")] Heartbeat = 1,
    /// <summary>
    ///连接
    /// </summary>
    [pbr::OriginalName("CONNECT")] Connect = 2,
    /// <summary>
    ///挂起暂停
    /// </summary>
    [pbr::OriginalName("PAUSE")] Pause = 3,
    /// <summary>
    ///恢复连接
    /// </summary>
    [pbr::OriginalName("RESTORE")] Restore = 4,
    /// <summary>
    ///断开连接
    /// </summary>
    [pbr::OriginalName("BREAK")] Break = 5,
    /// <summary>
    ///系统设置请求协议号
    /// </summary>
    [pbr::OriginalName("SETTING_REQ")] SettingReq = 10001,
    /// <summary>
    ///系统设置请求回包协议号
    /// </summary>
    [pbr::OriginalName("SETTING_RES")] SettingRes = 10002,
    /// <summary>
    ///实验信息请求协议号
    /// </summary>
    [pbr::OriginalName("EXPINFO_REQ")] ExpinfoReq = 10003,
    /// <summary>
    ///实验信息请求回包协议号
    /// </summary>
    [pbr::OriginalName("EXPINFO_RES")] ExpinfoRes = 10004,
    /// <summary>
    ///窗口唤醒请求
    /// </summary>
    [pbr::OriginalName("WINDOWWAKEUP_REQ")] WindowwakeupReq = 10005,
    /// <summary>
    ///窗口唤醒回执
    /// </summary>
    [pbr::OriginalName("WINDOWWAKEUP_RES")] WindowwakeupRes = 10006,
  }

  #endregion

}

#endregion Designer generated code
